name: Test available context

on:
  workflow_call:
    inputs:
      my_input:
        description: Dummy input
        required: true
        type: string
        options:
          - "test"
          - "something"

jobs:
  dummy:
    environment:
      name: ${{ inputs.my_input }}
    runs-on: ubuntu-latest
    env:
      CUSTOM_ENV: ${{ inputs.my_input }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          env
          echo "Full event"
          cat ${{ github.event_path }}
          ls
